### PR TITLE
Add a tooltip of the properties of each button

### PR DESCRIPTION
**Pull request by 1Evolve**
## Description

Add a tooltip of the properties of each button

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Review by TonybynMp4 — COMMENTED** [review]
Looks kinda weird tbh

**Comment by TonybynMp4** [comment]
What you think about it @mafewtm my UI judge ?

**Comment by BerkieBb** [comment]
@1Evolve can you make a screenshot of how the tooltip looks?

**Comment by mafewtm** [comment]
Not merging at this time.

**Pull request closed without merging**
